### ISSUE TITLE
wrong training

### ISSUE THREAD

**Issue by wojiaoyanmin** [DQiaole/ZITS_inpainting#11]
您好，出错的地方是继承自nn.modulem，kwags是设置为config.training_model，lama里的training_model这些参数在什么地方应用请问？请问出错原因？

root@dl-1558365045-pod-jupyter-8489459f68-rjkx2:~/share/program/ZITS_inpainting-main# python FTR_train.py --nodes 1 --gpus 1 --GPU_ids '0' --path ./ckpt/lama_places2 --config_file ./config_list/config_LAMA.yml --lama
here {'visualize_each_iters': 1000, 'concat_mask': True, 'store_discr_outputs_for_vis': True}
Traceback (most recent call last):
  File "FTR_train.py", line 101, in <module>
    mp.spawn(main_worker, nprocs=args.world_size, args=(args,))
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/share/program/ZITS_inpainting-main/FTR_train.py", line 52, in main_worker
    model = LaMa(config, gpu, rank)
  File "/root/share/program/ZITS_inpainting-main/src/FTR_trainer.py", line 26, in __init__
    self.inpaint_model = LaMaInpaintingTrainingModule(config, gpu=gpu, rank=rank, test=test, **kwargs).to(gpu)
  File "/root/share/program/ZITS_inpainting-main/src/models/FTR_model.py", line 320, in __init__
    super().__init__(*args, gpu=gpu, name='InpaintingModel', rank=rank, test=test, **kwargs)
  File "/root/share/program/ZITS_inpainting-main/src/models/FTR_model.py", line 34, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'visualize_each_iters'

**Comment by DQiaole** [comment]
Hi~
These parameters are useless, I have updated the config_LAMA.yml.
Thank you for your question.
