### ISSUE TITLE
Is there a demo code to make inference on custom image and mask

### ISSUE THREAD

**Issue by yijingru** [DQiaole/ZITS_inpainting#38]
Hi, I tried single_image_test.py, but it is hard coded for Places 365 Standard. Is there any simpler demo code to show the results based on a pair of inputs such as image and corresponding mask?

**Comment by DQiaole** [comment]
```
python single_image_test.py --path <ckpt_path> --config_file <config_path> \
 --GPU_ids '0' --img_path ./image.png --mask_path ./mask.png --save_path ./
```
the img_path and mask_path indicate a pair of inputs such as image and corresponding mask.

**Comment by yijingru** [comment]
Thanks! Do you have a template `config_file` for custom image and mask, I tried `config_ZITS_places2.yml `and it has error like this
```
BaseInpaintingTrainingModule init called
Loading InpaintingModel StructureUpsampling...
Loading trained transformer...
Loading InpaintingModel generator...
Warnning: There is no previous optimizer found. An initialized optimizer will be used.
Warnning: There is no previous optimizer found. An initialized optimizer will be used.
Traceback (most recent call last):
  File "single_image_test.py", line 322, in <module>
    model = ZITS(config, 0, 0, True)
  File "ZITS_inpainting/src/FTR_trainer.py", line 296, in __init__
    min_sigma=min_sigma, max_sigma=max_sigma)
  File "ZITS_inpainting/datasets/dataset_FTR.py", line 178, in __init__
    f = open(flist, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/wmlce/places365_standard/places2_all/test_sub_list.txt'
```

**Comment by DQiaole** [comment]
Hi, you can just comment out this line (line 291-297).

**Comment by yijingru** [comment]
Thanks a lot for the instruction! I used image size 512x512x3 and previous problem was resolved. However, image size 500x750x3 will have another problem. Do you know why?

```
load HAWP
Traceback (most recent call last):
  File "single_image_test.py", line 332, in <module>
    test(model, wf, args.img_path, args.mask_path, args.save_path, 0.85, sigma256=3.0)
  File "single_image_test.py", line 265, in test
    items = model.inpaint_model(items)
  File "/home/ubuntu/zits_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ZITS_inpainting/src/models/FTR_model.py", line 439, in forward
    batch['predicted_image'] = self.generator(masked_img.to(torch.float32), rel_pos_emb, direct_emb, str_feats)
  File "/home/ubuntu/zits_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ZITS_inpainting/src/models/LaMa.py", line 167, in forward
    x = self.conv2(x + str_feats[0])
RuntimeError: The size of tensor a (500) must match the size of tensor b (496) at non-singleton dimension 3
```

**Comment by DQiaole** [comment]
Because 500 is not a multiple of 8; so after downsampling and upsampling, there is a loss of resolution.

**Comment by yijingru** [comment]
Got it! Thanks!
